[package]
name = "test_program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = { version = "2.1.4", features = ["solana-sha256-hasher"] }
solana-pubkey = "2.1.4" # Adjust the version as necessary
