# src/anaheim-worker/src/auto_patch_worker.py
import subprocess
import json
from pathlib import Path
import re

PROJECT_PATH = Path("../anaheim-putsch-self-governance-solana-dapp")

# -----------------------
# Branches
# -----------------------
ORION = "Orion"
ORION_EXPLORATION = "Orion-Exploration"
ROOTS = "Roots"
YEW = "Yew"
MAIN = "main"

# -----------------------
# Seuils de sécurité
# -----------------------
MAX_ERRORS = 30
MAX_WARNINGS = 100
FORCE_PATCH = True

# -----------------------
# Types à ignorer automatiquement
# -----------------------
AUTO_IGNORE = ["unused variable", "console.log"]

# -----------------------
# Worker Functions
# -----------------------

def run_tsc():
    errors_path = PROJECT_PATH / "ts-errors.log"
    subprocess.run(
        ["npx", "tsc", "--noEmit", "--pretty", "false"],
        cwd=PROJECT_PATH,
        stdout=open(errors_path, "w"),
        stderr=subprocess.STDOUT,
        check=False
    )
    return errors_path

def parse_errors(errors_file: Path):
    errors = 0
    warnings = 0
    details = []
    with open(errors_file, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            if any(ignore in line for ignore in AUTO_IGNORE):
                continue
            if "error" in line.lower():
                errors += 1
                details.append(f"ERROR: {line}")
            elif "warning" in line.lower():
                warnings += 1
                details.append(f"WARNING: {line}")
    return errors, warnings, details

def run_resolver(errors_file: Path):
    result = subprocess.run(
        ["node", "src/utils/resolver/index.js", str(errors_file)],
        cwd=PROJECT_PATH,
        capture_output=True,
        text=True,
        check=False
    )
    if result.stdout.strip():
        return json.loads(result.stdout)
    else:
        print("⚠️ Resolver n'a rien renvoyé:", result.stderr)
        return []

# -----------------------
# Patch Functions
# -----------------------

def insert_import(file_path: Path, symbol: str):
    code = file_path.read_text()
    if re.search(rf"import\s+.*\b{symbol}\b", code):
        return False
    new_import = f"import {{ {symbol} }} from './{file_path.stem}';\n"
    file_path.write_text(new_import + code)
    return True

def create_function(file_path: Path, symbol: str):
    file_path.parent.mkdir(parents=True, exist_ok=True)
    code = file_path.read_text() if file_path.exists() else ""
    skeleton = f"""\n// Auto-generated by worker
export function {symbol}(...args: any[]): void {{
  throw new Error("Function {symbol} not implemented");
}}
"""
    file_path.write_text(code + skeleton)
    return True

def patch_function_signature(file_path: Path, function_name: str, new_param: str, new_type: str = "any"):
    code = file_path.read_text()
    pattern = rf"(function\s+{function_name}\s*\([^)]*)\)"
    match = re.search(pattern, code)
    if not match:
        return False
    before = match.group(1)
    updated = before + f", {new_param}: {new_type})"
    file_path.write_text(code[:match.start()] + updated + code[match.end():])
    return True

def patch_type_annotation(file_path: Path, symbol: str, new_type: str):
    code = file_path.read_text()
    pattern = rf"(\b{symbol}\s*:\s*)[A-Za-z0-9_\[\]\|]+"
    new_code, n = re.subn(pattern, rf"\1{new_type}", code)
    if n == 0:
        return False
    file_path.write_text(new_code)
    return True

def apply_actions(actions):
    for act in actions:
        action = act.get("action")
        file_path = PROJECT_PATH / act.get("file", "")
        if action == "add_import":
            insert_import(file_path, act["symbol"])
        elif action == "suggest_package":
            subprocess.run(["pnpm", "add", act["package"]], cwd=PROJECT_PATH)
        elif action == "create_function":
            create_function(file_path, act["symbol"])
        elif action == "create_parameter":
            fn = act.get("function", "unknownFn")
            param = act.get("param", "arg")
            ptype = act.get("type", "any")
            patch_function_signature(file_path, fn, param, ptype)
        elif action == "change_type":
            symbol = act.get("symbol", "arg")
            new_type = act.get("newType", "any")
            patch_type_annotation(file_path, symbol, new_type)

# -----------------------
# Interactive patch
# -----------------------

def interactive_apply(actions, branch):
    print(f"💡 Mode interactif activé pour la branche {branch}")
    batch_accept = {}
    for i, act in enumerate(actions, 1):
        action_type = act.get("action")
        file_path = PROJECT_PATH / act.get("file", "")
        symbol = act.get("symbol", "")

        # Si batch a été choisi pour ce type, appliquer automatiquement
        if batch_accept.get(action_type, False):
            apply_actions([act])
            print(f"✅ Fix batch appliqué: {action_type} sur {file_path}")
            continue

        print(f"{i}/{len(actions)}: Action: {action_type}, File: {file_path}, Symbol: {symbol}")
        user_input = input("Appliquer ce fix ? [y/N/b=Batch for type]: ").strip().lower()
        if user_input == "y":
            apply_actions([act])
            print("✅ Fix appliqué")
        elif user_input == "b":
            batch_accept[action_type] = True
            apply_actions([act])
            print(f"✅ Batch activé pour {action_type}, fix appliqué")
        else:
            print("❌ Fix ignoré")

# -----------------------
# Git Helpers
# -----------------------

def get_current_branch():
    result = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"],
                            cwd=PROJECT_PATH, capture_output=True, text=True)
    return result.stdout.strip()

def checkout_branch(branch_name: str):
    subprocess.run(["git", "checkout", branch_name], cwd=PROJECT_PATH)

def commit_and_push(branch_name: str, message: str):
    subprocess.run(["git", "add", "."], cwd=PROJECT_PATH)
    subprocess.run(["git", "commit", "-m", message], cwd=PROJECT_PATH)
    subprocess.run(["git", "push", "origin", branch_name], cwd=PROJECT_PATH)

def propagate_to_yew():
    checkout_branch(YEW)
    subprocess.run(["git", "merge", ORION, "--no-ff"
                                           "", "-m", "Merge fixes depuis Orion"], cwd=PROJECT_PATH)

# -----------------------
# Main
# -----------------------

def main():
    branch = get_current_branch()
    print(f"🌿 Branche active : {branch}")

    errors_file = run_tsc()
    errors, warnings, details = parse_errors(errors_file)
    print(f"⚠️ TS Errors: {errors}, Warnings: {warnings}")

    log_file = PROJECT_PATH / "ts-errors-detailed.log"
    with open(log_file, "w") as f:
        f.write("\n".join(details))
    print(f"📝 Log complet enregistré dans {log_file}")

    actions = run_resolver(errors_file)

    if branch in [ORION, ORION_EXPLORATION]:
        if (errors > MAX_ERRORS or warnings > MAX_WARNINGS) and not FORCE_PATCH:
            print(f"❌ Trop d'erreurs ou warnings, patch stoppé. Fix manuellement.")
            return
        if actions:
            print(f"🔎 {len(actions)} action(s) détectée(s), application automatique...")
            apply_actions(actions)
            propagate_to_yew()
            commit_and_push(YEW, "✅ Fixes automatiques appliqués depuis worker")
        else:
            print("✅ Aucun fix détecté.")

    elif branch in [YEW, MAIN]:
        if actions:
            interactive_apply(actions, branch)
        else:
            print("✅ Aucun fix détecté.")

    elif branch == ROOTS:
        print("⚠️ Roots est branch live, ne pas patcher directement. Utiliser Orion.")
    else:
        print(f"⚠️ Branche {branch} inconnue. Vérifier le workflow.")

if __name__ == "__main__":
    main()
