# anarcrypt.sol/anaheim-worker/worker.py
import subprocess
import json
from pathlib import Path
import re

PROJECT_PATH = Path("../anaheim-putsch-self-governance-solana-dapp")

# -----------------------
# Helpers
# -----------------------

def run_tsc():
    """Compile avec tsc et capture les erreurs dans un fichier."""
    errors_path = PROJECT_PATH / "ts-errors.log"
    with open(errors_path, "w") as f:
        subprocess.run(
            ["npx", "tsc", "--noEmit"],
            cwd=PROJECT_PATH,
            stdout=f,
            stderr=subprocess.STDOUT,
            check=False
        )
    return errors_path

def run_resolver(errors_file: Path):
    """Appelle le resolver TS et retourne les actions JSON."""
    result = subprocess.run(
        ["node", "src/utils/resolver/index.js", str(errors_file)],
        cwd=PROJECT_PATH,
        capture_output=True,
        text=True,
        check=False
    )
    if result.stdout.strip():
        return json.loads(result.stdout)
    else:
        print("⚠️ Resolver n'a rien renvoyé:", result.stderr)
        return []

# -----------------------
# Patches
# -----------------------

def insert_import(file_path: Path, symbol: str):
    """Ajoute un import manquant au début du fichier."""
    code = file_path.read_text()
    if re.search(rf"import\s+.*\b{symbol}\b", code):
        print(f"ℹ️ Import {symbol} déjà présent dans {file_path}")
        return False
    new_import = f"import {{ {symbol} }} from './{file_path.stem}';\n"
    new_code = new_import + code
    file_path.write_text(new_code)
    print(f"✅ Import ajouté: {symbol} -> {file_path}")
    return True

def create_function(file_path: Path, symbol: str):
    """Crée une fonction squelette dans le fichier cible."""
    file_path.parent.mkdir(parents=True, exist_ok=True)
    code = file_path.read_text() if file_path.exists() else ""
    if re.search(rf"(function|export function)\s+{symbol}\s*\(", code):
        print(f"ℹ️ Fonction {symbol} existe déjà dans {file_path}")
        return False
    skeleton = f"""\n// Auto-generated by worker
export function {symbol}(...args: any[]): void {{
  throw new Error("Function {symbol} not implemented");
}}
"""
    file_path.write_text(code + skeleton)
    print(f"🛠 Fonction squelette créée: {symbol} -> {file_path}")
    return True

def patch_function_signature(file_path: Path, function_name: str, new_param: str, new_type: str = "any"):
    """Ajoute un paramètre manquant à une fonction existante."""
    code = file_path.read_text()
    pattern = rf"(function\s+{function_name}\s*\([^)]*)\)"
    match = re.search(pattern, code)
    if not match:
        print(f"❌ Fonction {function_name} non trouvée dans {file_path}")
        return False
    before = match.group(1)
    updated = before + f", {new_param}: {new_type})"
    new_code = code[:match.start()] + updated + code[match.end():]
    file_path.write_text(new_code)
    print(f"➕ Paramètre ajouté à {function_name}: {new_param}: {new_type}")
    return True

def patch_type_annotation(file_path: Path, symbol: str, new_type: str):
    """Remplace une annotation de type d’un symbole existant."""
    code = file_path.read_text()
    pattern = rf"(\b{symbol}\s*:\s*)[A-Za-z0-9_\[\]\|]+"
    new_code, n = re.subn(pattern, rf"\1{new_type}", code)
    if n == 0:
        print(f"❌ Type pour {symbol} non trouvé dans {file_path}")
        return False
    file_path.write_text(new_code)
    print(f"🔧 Type de {symbol} changé en {new_type} -> {file_path}")
    return True

# -----------------------
# Dispatcher
# -----------------------

def apply_actions(actions):
    """Applique automatiquement les actions proposées par le resolver."""
    for act in actions:
        action = act.get("action")
        if action == "add_import":
            target_file = PROJECT_PATH / act["file"]
            insert_import(target_file, act["symbol"])

        elif action == "suggest_package":
            print(f"📦 Installer package suggéré: {act['package']} (symbol {act['symbol']})")
            subprocess.run(["pnpm", "add", act["package"]], cwd=PROJECT_PATH)

        elif action == "create_function":
            target_file = PROJECT_PATH / act["file"]
            create_function(target_file, act["symbol"])

        elif action == "create_parameter":
            target_file = PROJECT_PATH / act["file"]
            fn = act.get("function", "unknownFn")
            param = act.get("param", "arg")
            ptype = act.get("type", "any")
            patch_function_signature(target_file, fn, param, ptype)

        elif action == "change_type":
            target_file = PROJECT_PATH / act["file"]
            symbol = act.get("symbol", "arg")
            new_type = act.get("newType", "any")
            patch_type_annotation(target_file, symbol, new_type)

        else:
            print(f"ℹ️ Ignoré: {act}")

# -----------------------
# Main
# -----------------------

def main():
    print("🚀 Lancement du worker TypeScript resolver...")
    errors_file = run_tsc()
    actions = run_resolver(errors_file)
    if not actions:
        print("✅ Aucun fix détecté.")
        return
    print(f"🔎 {len(actions)} action(s) proposées:")
    apply_actions(actions)

if __name__ == "__main__":
    main()
